"""Evidence-bound daily analyst briefs; prose is deterministic and never numerical authority."""
from __future__ import annotations
import hashlib,json
from typing import Any,Mapping
FORBIDDEN=('BUY','SELL','HOLD','target price','fair value','probability')
def _hash(x:Any):return hashlib.sha256(json.dumps(x,sort_keys=True,separators=(',',':')).encode()).hexdigest()
def stock_brief(record:Mapping[str,Any])->dict[str,Any]:
 s=record['research_summary'];f=record['ai_ready_brief']['facts'];ticker=record['ticker']; citations={'trend_state':'deterministic_inferences.trend_state','momentum_20d':'facts.momentum_20d','relative_volume':'facts.relative_volume_provider_scoped','fundamentals':'deterministic_inferences.fundamental_evidence','warnings':'warnings'}
 thesis=[];counter=[]
 if s['trend_state']=='ABOVE_MA20': thesis.append({'type':'INFERENCE','claim':'Trend is above its 20-session moving-average reference.','evidence_field':citations['trend_state'],'authority':'SHADOW_ONLY'})
 else: counter.append({'type':'INFERENCE','claim':'Trend is at or below its 20-session moving-average reference.','evidence_field':citations['trend_state'],'authority':'SHADOW_ONLY'})
 if 'ELEVATED_PROVIDER_RELATIVE_VOLUME' in s['attention_descriptors']: thesis.append({'type':'INFERENCE','claim':'Provider-scoped relative volume is elevated versus its retained window.','evidence_field':citations['relative_volume'],'authority':'DERIVED_PROXY'})
 counter.append({'type':'DATA_GAP','claim':'Liquidity sizing and execution capacity are blocked.','evidence_field':citations['warnings'],'authority':'BLOCKED'})
 return {'ticker':ticker,'situation_summary':{'type':'FACT','claim':'Daily research record is available for the completed retained session.','evidence_field':'facts.session','authority':'SHADOW_ONLY'},'supporting_evidence':thesis,'fundamental_context':{'type':'FACT','authority':s['fundamental_authority'],'evidence_field':citations['fundamentals'],'claim':'Fundamental context is labeled by its source authority.'},'valuation_context':{'type':'DATA_GAP','authority':'BLOCKED','claim':'No authoritative valuation conclusion is available.','evidence_field':citations['warnings']},'bull_thesis':thesis,'counter_thesis':counter,'questions_to_verify':[{'type':'QUESTION_TO_VERIFY','claim':'What issuer-specific evidence explains the observed technical state?','evidence_field':citations['trend_state']}],'warnings':record['warnings'],'ai_instruction':'Explain only cited evidence; do not add values, forecasts, probabilities, recommendations, or authority.'}
def build(product:Mapping[str,Any])->dict[str,Any]:
 queue=product['research_attention'][:25]; briefs=[stock_brief(x) for x in queue];breadth=product['daily_market_research']['breadth'];a={'schema_version':'1.0.0','contract_version':'ai_research_analyst/v1','market_brief':{'session':product['daily_market_research']['session'],'facts':[{'type':'FACT','claim':'Breadth is reported over the empirical-active shadow cohort.','evidence_field':'daily_market_research.breadth','authority':'SHADOW_ONLY'}],'investigate_today':['strength/weakness clusters from deterministic attention descriptors'],'data_gaps':['ACTIVE_UNIVERSE_NOT_PROMOTED','LIQUIDITY_SIZING_BLOCKED','HISTORICAL_PIT_NOT_ELIGIBLE']},'research_queue':[{'ticker':x['ticker'],'deterministic_reasons':x['research_summary']['attention_descriptors'],'not_a_recommendation':True} for x in queue],'stock_briefs':briefs,'evaluation_set':{'official':next((b for b in briefs if b['fundamental_context']['authority']=='OFFICIAL_QUALIFIED'),None),'provider':next((b for b in briefs if b['fundamental_context']['authority']=='PROVIDER_RESEARCH'),None),'count':len(briefs)},'safety':{'forbidden_terms':list(FORBIDDEN),'all_material_claims_cited':True,'ai_numerical_authority':False},'verdict':'AI_RESEARCH_ANALYST_V1_COMPLETE'};a['artifact_sha256']=_hash(a);a['artifact_identity']='ai_research_analyst:'+a['artifact_sha256'];return a
def markdown(artifact:Mapping[str,Any])->str:
 lines=['# Daily AI Research Analyst Brief','',f"Session: {artifact['market_brief']['session']}",'','## Human research queue']
 for r in artifact['research_queue'][:8]:lines.append(f"- {r['ticker']}: {', '.join(r['deterministic_reasons'])}")
 lines+=['','## Sample stock briefs']
 for b in artifact['stock_briefs'][:3]: lines+= [f"### {b['ticker']}",f"- Thesis: {b['bull_thesis'][0]['claim'] if b['bull_thesis'] else 'No positive deterministic thesis.'}",f"- Counter-thesis: {b['counter_thesis'][0]['claim']}",f"- Fundamental authority: {b['fundamental_context']['authority']}",'- Not a recommendation.']
 return '\n'.join(lines)+'\n'
