"""DNSE Daily Volume Composition Reconciliation — P0-B.2A-B.2B + P0-B.2B1.

Reconciles authoritative daily OHLC ``v`` against board-level Trades history
across a configurable candidate set.

Scope
-----
- C1–C4: additive board-aggregation candidates from the original P0-B.2A-B.2B
  milestone.  Their failure on the real corpus is preserved and NOT hidden.
- C5:    SCALED_G1 shadow candidate introduced by P0-B.2B1.  The scale is
  data/config-driven and does NOT assert "Trades quantity unit = 10 shares"
  as an authority claim.  ``semantic_unit_interpretation = UNKNOWN`` is
  mandatory; the scale is recorded as EMPIRICAL_CANDIDATE only.

Provenance note
---------------
The canonical Trades corpus consumed here was generated by the code at commit
``2b7b38772e16c434c8adf5288cbc46ef0f7f4c02``
(``dnse_trades_canonical_shadow.py`` on branch
``feature/trades-canonical-columnar-shadow-v1``).  That commit is NOT in the
ancestry of the current P0-B worktree main HEAD.  The lineage status is
therefore recorded as SOURCE_GENERATOR_NOT_IN_CURRENT_MAIN_ANCESTRY, which
must remain visible for any future promotion review.
"""

from __future__ import annotations

import json
from dataclasses import dataclass, field
from enum import Enum
from pathlib import Path
from typing import Any

import pandas as pd

from market_phase2_foundation import DNSE_BOARD_SEMANTICS

import vn_time


# ---------------------------------------------------------------------------
# Provenance constants
# ---------------------------------------------------------------------------

#: Commit that generated the canonical Trades corpus used by this module.
#: Not reachable from the current worktree/main HEAD.
CANONICAL_TRADES_SOURCE_COMMIT = "2b7b38772e16c434c8adf5288cbc46ef0f7f4c02"

#: Lineage status of the Trades source generator relative to current HEAD.
CANONICAL_TRADES_LINEAGE_STATUS = "SOURCE_GENERATOR_NOT_IN_CURRENT_MAIN_ANCESTRY"


# ---------------------------------------------------------------------------
# C5 / SCALED_G1 candidate contract
# ---------------------------------------------------------------------------

class CandidateType(str, Enum):
    ADDITIVE_BOARD_SUM = "ADDITIVE_BOARD_SUM"
    SCALED_G1 = "SCALED_G1"


class ScaleStatus(str, Enum):
    EMPIRICAL_CANDIDATE = "EMPIRICAL_CANDIDATE"
    VALIDATED_SHADOW = "VALIDATED_SHADOW"


@dataclass(frozen=True)
class ScaledG1Candidate:
    """Contract for a SCALED_G1 shadow candidate.

    The ``empirical_scale`` is config/data-driven.  Changing the value here
    produces a different, still-deterministic evaluation.  The scale does NOT
    assert the semantic meaning of the Trades quantity unit — that remains
    UNKNOWN and must not be silently promoted.
    """

    candidate_id: str
    candidate_type: CandidateType
    empirical_scale: float
    scale_status: ScaleStatus
    semantic_unit_interpretation: str
    evidence_source: str

    def compute(self, g1_quantity: float) -> float:
        return self.empirical_scale * g1_quantity

    def record(self) -> dict[str, Any]:
        return {
            "candidate_id": self.candidate_id,
            "candidate_type": self.candidate_type.value,
            "empirical_scale": self.empirical_scale,
            "scale_status": self.scale_status.value,
            "semantic_unit_interpretation": self.semantic_unit_interpretation,
            "evidence_source": self.evidence_source,
        }


#: The single registered C5 candidate.  ``semantic_unit_interpretation`` is
#: UNKNOWN; this is not a claim that "1 Trades unit = 10 shares".
C5_CANDIDATE = ScaledG1Candidate(
    candidate_id="C5",
    candidate_type=CandidateType.SCALED_G1,
    empirical_scale=10.0,
    scale_status=ScaleStatus.EMPIRICAL_CANDIDATE,
    semantic_unit_interpretation="UNKNOWN",
    evidence_source=(
        "p0-b2ab-zero-match-root-cause-diagnosis-v1-20260818: "
        "daily_v / board_G1_quantity clusters at exactly 10.0 "
        "across 35,164/35,231 (99.8098%) symbol-sessions "
        "over 40 retained trading dates; scale discovered from data, "
        "not from a provider unit assertion"
    ),
)


# ---------------------------------------------------------------------------
# Residual classification
# ---------------------------------------------------------------------------

class ResidualClass(str, Enum):
    POSITIVE_DELTA_MULTIPLE_OF_100 = "POSITIVE_DELTA_MULTIPLE_OF_100"
    NEGATIVE_DELTA_MINUS_4 = "NEGATIVE_DELTA_MINUS_4"
    OTHER = "OTHER"
    EXACT_MATCH = "EXACT_MATCH"  # no residual


def classify_c5_residual(delta: float) -> ResidualClass:
    """Classify a single C5 residual deterministically.

    ``delta = daily_v - C5``

    Classes
    -------
    EXACT_MATCH
        delta == 0 (no residual).
    POSITIVE_DELTA_MULTIPLE_OF_100
        delta > 0 AND delta is an exact integer multiple of 100.
        Consistent with a small number of G1 executions present in ``v``
        but absent from the canonical Trades corpus for that symbol/session.
        True root cause NOT established; prior hypothesis (Task-160 27 known
        REMAINING_FAILED units) was tested and ruled out (0/67 overlap).
    NEGATIVE_DELTA_MINUS_4
        delta == -4 exactly.
        Empirically observed on SHB and VIX only across the 40-session corpus.
        Root cause NOT established by this milestone.
    OTHER
        All remaining mismatches.  Do NOT invent an explanation.
    """
    if delta == 0.0:
        return ResidualClass.EXACT_MATCH
    if delta > 0 and delta % 100 == 0:
        return ResidualClass.POSITIVE_DELTA_MULTIPLE_OF_100
    if delta == -4.0:
        return ResidualClass.NEGATIVE_DELTA_MINUS_4
    return ResidualClass.OTHER


# ---------------------------------------------------------------------------
# C1–C4 definitions (preserved unmodified from P0-B.2A-B.2B)
# ---------------------------------------------------------------------------

CANDIDATE_DEFINITIONS: dict[str, list[str]] = {
    "C1": ["G1"],
    "C2": ["G1", "G4"],
    "C3": ["G1", "T1", "T3"],
    "C4": ["G1", "G4", "T1", "T3", "T4", "T6"],
}


# ---------------------------------------------------------------------------
# Data loaders
# ---------------------------------------------------------------------------

def load_canonical_trades(
    trades_dir: Path | str,
    session_date: str | None = None,
) -> pd.DataFrame:
    """Load canonical Trades from the materialization directory.

    Provenance: the generating code lives at
    ``CANONICAL_TRADES_SOURCE_COMMIT`` on a divergent worktree branch;
    the lineage status is ``CANONICAL_TRADES_LINEAGE_STATUS``.
    """
    trades_dir = Path(trades_dir)
    if session_date:
        path = trades_dir / f"session_date={session_date}" / "part-00000.parquet"
        if not path.exists():
            return pd.DataFrame()
        return pd.read_parquet(path)
    # Multi-session: read all session-date partitions
    frames = []
    for partition in sorted(trades_dir.glob("session_date=*")):
        p = partition / "part-00000.parquet"
        if p.exists():
            frames.append(pd.read_parquet(p))
    return pd.concat(frames, ignore_index=True) if frames else pd.DataFrame()


def extract_ohlc_daily_v(
    ohlc_dir: Path | str,
    symbol: str | None = None,
) -> pd.DataFrame:
    """Extract daily ``v`` from retained raw OHLC parquet files.

    Returns one row per (symbol, session_date) — deduplicated; earlier
    observation wins on exact duplicates.
    """
    ohlc_dir = Path(ohlc_dir)
    records: list[dict[str, Any]] = []

    files = list(ohlc_dir.glob("**/*.parquet"))
    if not files:
        return pd.DataFrame()

    for f in files:
        try:
            df = pd.read_parquet(f)
            for _, row in df.iterrows():
                inst = row.get("instrument")
                if symbol and inst != symbol:
                    continue
                payload = json.loads(row.get("raw_payload_json", "{}"))
                t_arr = payload.get("t", [])
                v_arr = payload.get("v", [])
                if not t_arr or not v_arr or len(t_arr) != len(v_arr):
                    continue
                dates = (
                    pd.to_datetime(t_arr, unit="s", utc=True)
                    .tz_convert(vn_time.VN_TZ)
                    .strftime("%Y-%m-%d")
                )
                for d, v in zip(dates, v_arr):
                    records.append(
                        {
                            "symbol": inst,
                            "session_date": d,
                            "daily_v": v,
                            "ohlc_observation_id": row.get("observation_id"),
                        }
                    )
        except Exception:  # noqa: BLE001  — retain partial results
            pass

    if not records:
        return pd.DataFrame()
    return (
        pd.DataFrame(records)
        .drop_duplicates(subset=["symbol", "session_date"], keep="first")
    )


# ---------------------------------------------------------------------------
# Core reconciliation engine
# ---------------------------------------------------------------------------

def reconcile_volume(
    trades_df: pd.DataFrame,
    ohlc_df: pd.DataFrame,
    *,
    c5_candidate: ScaledG1Candidate = C5_CANDIDATE,
    source_commit: str = CANONICAL_TRADES_SOURCE_COMMIT,
    lineage_status: str = CANONICAL_TRADES_LINEAGE_STATUS,
) -> pd.DataFrame:
    """Reconcile volume composition for every complete eligible symbol-session.

    Parameters
    ----------
    trades_df:
        Canonical Trades DataFrame with columns ``symbol``, ``session_date``,
        ``board_id``, ``quantity``.
    ohlc_df:
        OHLC DataFrame with columns ``symbol``, ``session_date``, ``daily_v``,
        ``ohlc_observation_id``.
    c5_candidate:
        The SCALED_G1 candidate contract.  Changing ``empirical_scale`` here
        produces a deterministic evaluation at a different scale without
        touching C1–C4 logic.
    source_commit, lineage_status:
        Provenance metadata recorded in every output row.

    Returns
    -------
    pd.DataFrame
        One row per eligible (symbol, session_date) intersection.
        - C1–C4 failures are NOT hidden; their delta and exact_match columns
          remain in every row unmodified.
        - C5 columns and residual_class are appended.
        - Provenance columns (source_commit, lineage_status) are appended.
        - ``qualified_liquidity_inputs`` is always False; C5 shadow validation
          does NOT promote volume authority.
    """
    if trades_df.empty or ohlc_df.empty:
        return pd.DataFrame()

    # Aggregate per (symbol, session_date, board_id)
    board_vols = (
        trades_df
        .groupby(["symbol", "session_date", "board_id"])["quantity"]
        .sum()
        .reset_index()
    )

    pivot_vols = board_vols.pivot_table(
        index=["symbol", "session_date"],
        columns="board_id",
        values="quantity",
        fill_value=0,
    ).reset_index()

    # Inner join: symbols absent from either side are excluded (never zero-filled)
    merged = pd.merge(ohlc_df, pivot_vols, on=["symbol", "session_date"], how="inner")

    results: list[dict[str, Any]] = []
    for _, row in merged.iterrows():
        symbol = row["symbol"]
        session_date = row["session_date"]
        daily_v = float(row["daily_v"])

        g1 = float(row.get("G1", 0) or 0)
        g4 = float(row.get("G4", 0) or 0)
        t1 = float(row.get("T1", 0) or 0)
        t3 = float(row.get("T3", 0) or 0)
        t4 = float(row.get("T4", 0) or 0)
        t6 = float(row.get("T6", 0) or 0)

        # ---- C1–C4 (preserved from P0-B.2A-B.2B) ----
        c1 = g1
        c2 = g1 + g4
        c3 = g1 + t1 + t3
        c4 = g1 + g4 + t1 + t3 + t4 + t6

        candidates_c1_c4 = {"C1": c1, "C2": c2, "C3": c3, "C4": c4}
        deltas_c1_c4 = {k: daily_v - v for k, v in candidates_c1_c4.items()}
        exact_c1_c4 = {k: d == 0.0 for k, d in deltas_c1_c4.items()}

        # ---- C5 (SCALED_G1 shadow candidate) ----
        c5 = c5_candidate.compute(g1)
        delta_c5 = daily_v - c5
        exact_c5 = delta_c5 == 0.0
        residual_class = classify_c5_residual(delta_c5)

        # ---- Discrimination ----
        # The C1-C4 sums above already follow the canonical board contract.
        # These legacy predicate labels did not: G4 is odd-lot, while every
        # T-board is put-through (T4/T6 are also odd-lot).
        board_quantities = {"G1": g1, "G4": g4, "T1": t1, "T3": t3, "T4": t4, "T6": t6}
        has_continuous = board_quantities["G1"] > 0
        has_put_through = any(
            board_quantities[code] > 0
            for code, meaning in DNSE_BOARD_SEMANTICS.items()
            if meaning.startswith("PUT_THROUGH")
        )
        has_odd_lot = any(
            board_quantities[code] > 0
            for code, meaning in DNSE_BOARD_SEMANTICS.items()
            if "ODD_LOT" in meaning
        )
        discriminating = has_continuous and has_put_through and has_odd_lot

        # ---- C1–C4 verdict (unchanged from original milestone) ----
        if not discriminating:
            verdict_c1_c4 = "INSUFFICIENT_DISCRIMINATION"
        elif any(exact_c1_c4.values()):
            verdict_c1_c4 = "VALIDATED_READY_FOR_P0_B2D_REVIEW"
        else:
            verdict_c1_c4 = "CONFLICTING"

        results.append(
            {
                # identity
                "symbol": symbol,
                "session_date": session_date,
                # source
                "daily_v": daily_v,
                "board_G1": g1,
                "board_G4": g4,
                "board_T1": t1,
                "board_T3": t3,
                "board_T4": t4,
                "board_T6": t6,
                # C1–C4 (preserved, NOT retrospectively hidden)
                "C1": c1,
                "C2": c2,
                "C3": c3,
                "C4": c4,
                "delta_C1": deltas_c1_c4["C1"],
                "delta_C2": deltas_c1_c4["C2"],
                "delta_C3": deltas_c1_c4["C3"],
                "delta_C4": deltas_c1_c4["C4"],
                "exact_match_C1": exact_c1_c4["C1"],
                "exact_match_C2": exact_c1_c4["C2"],
                "exact_match_C3": exact_c1_c4["C3"],
                "exact_match_C4": exact_c1_c4["C4"],
                "verdict_c1_c4": verdict_c1_c4,
                # C5 (SCALED_G1 shadow)
                "C5": c5,
                "delta_C5": delta_c5,
                "exact_match_C5": exact_c5,
                "c5_empirical_scale": c5_candidate.empirical_scale,
                "c5_scale_status": c5_candidate.scale_status.value,
                "c5_semantic_unit_interpretation": c5_candidate.semantic_unit_interpretation,
                "c5_candidate_type": c5_candidate.candidate_type.value,
                "residual_class_C5": residual_class.value,
                # discrimination
                "discriminating_session": discriminating,
                # completeness (inner join guarantees both OHLC and Trades present)
                "completeness": "COMPLETE",
                # authority boundary — C5 shadow NEVER promotes liquidity authority
                "qualified_liquidity_inputs": False,
                # lineage
                "lineage_ohlc": row.get("ohlc_observation_id"),
                "canonical_trades_source_commit": source_commit,
                "canonical_trades_lineage_status": lineage_status,
            }
        )

    return pd.DataFrame(results)
