from __future__ import annotations
import hashlib, json
from pathlib import Path
from official_route_ownership_evidence import qualify
ROOT=Path(__file__).resolve().parent
def run():
 p14=json.loads((ROOT/'operations-review/p3f14-official-financial-source-discovery-20260820/p3f14_official_financial_source_discovery_artifact.json').read_text()); reg=json.loads((ROOT/'config/official_source_registry.json').read_text()); manifest=json.loads((ROOT/'operations-review/governed-official-evidence-v1/official_document_acquisition_manifest.json').read_text())
 cohort=[x['canonical_instrument'] for x in p14['route_candidate_inventory']]; rows=[x for x in manifest['records'] if x.get('acquisition_status')=='retained' and x.get('source_id')=='issuer_ir']
 proofs=[qualify({'canonical_instrument':x.get('ticker'),'issuer_legal_identity':x.get('ticker'),'profile_locator':x.get('canonical_url'),'candidate_locator':x.get('canonical_url'),'raw_document_sha256':x.get('sha256'),'ownership_evidence':'retained_official_document_locator'},reg) for x in rows[:3]]
 a={'schema_version':'1.0.0','contract_version':'official_route_ownership_evidence/v1','target_cohort_identity':{'derived_from':p14['artifact_identity'],'count':len(cohort)},'profile_identity_source_inventory':['approved issuer_ir retained manifest','approved registry'],'representative_proofs':proofs,'f14_compatibility':{'qualified_proofs':sum(x['route_approval_eligible'] for x in proofs),'registry_mutated':False},'cohort_scaleout_estimate':{'no_profile_identity_evidence':len(cohort),'likely_addressable':0},'newly_route_approval_eligible':0,'remaining_root_blockers':{'NO_RETAINED_OFFICIAL_PROFILE_OR_ISSUER_DOMAIN_OWNERSHIP_EVIDENCE':len(cohort)},'ticker_specific_branch_audit':{'status':'PASS','production_ticker_literals':[]},'ownership_evidence_gate':'OFFICIAL_ROUTE_OWNERSHIP_EVIDENCE_PARTIAL','next_gate':'RETAINED_OFFICIAL_EXCHANGE_PROFILE_OR_ISSUER_DOMAIN_OWNERSHIP_EVIDENCE','verdict':'P3F14B_ROUTE_OWNERSHIP_EVIDENCE_PARTIAL'};a['artifact_sha256']=hashlib.sha256(json.dumps(a,sort_keys=True,separators=(',',':')).encode()).hexdigest();a['artifact_identity']='p3f14b_route_ownership_evidence:'+a['artifact_sha256'];return a
