from __future__ import annotations
import hashlib,json
from pathlib import Path
ROOT=Path(__file__).resolve().parent
def run():
 b=json.loads((ROOT/'operations-review/p3f9b-market-wide-exact-session-scaleout-20260820/p3f7_mva_daily_research_bundle_exact_session.json').read_text(encoding='utf-8'));p10=json.loads((ROOT/'operations-review/p3f10-generic-fundamental-evidence-scaleout-20260820/p3f10_generic_fundamental_evidence_scaleout_artifact.json').read_text(encoding='utf-8'));disp={x['ticker']:x for x in p10['instrument_dispositions']};records=[]
 for r in b['records']:
  if not r.get('empirical_active_cohort_member'):continue
  t=r['identity']['canonical_ticker'];d=disp.get(t,{});v=r['market_features'].get('values',{});trend='ABOVE_MA20' if v.get('close',0)>v.get('ma_20',float('inf')) else 'AT_OR_BELOW_MA20'
  records.append({'ticker':t,'facts':{'session':r['session'],'close':v.get('close'),'momentum_20d':v.get('momentum_20d'),'volatility_20d':v.get('volatility_20d'),'relative_volume_provider_scoped':v.get('relative_volume_provider_scoped')},'deterministic_inferences':[{'category':'trend_state','value':trend,'authority':'SHADOW_ONLY'},{'category':'fundamental_evidence','value':'OFFICIAL_QUALIFIED' if d.get('evidence_state')=='EVIDENCE_QUALIFIED' else 'PROVIDER_RESEARCH','authority':'OFFICIAL_QUALIFIED' if d.get('evidence_state')=='EVIDENCE_QUALIFIED' else 'PROVIDER_RESEARCH'}],'data_warnings':r.get('warnings',[])+(['PROVIDER_FUNDAMENTALS_DESCRIPTIVE_ONLY'] if d.get('raw_observation_state')=='RAW_OBSERVED' and d.get('evidence_state')!='EVIDENCE_QUALIFIED' else []),'future_ai_narrative':None,'is_actionable_for_execution':False})
 a={'schema_version':'1.0.0','contract_version':'p3f18_mva_research_synthesis/v1','research_synthesis_contract':{'fact_warning_inference_separation':True,'future_ai_narrative_is_numerically_non_authoritative':True,'prohibited':['ranking','recommendation','target_price','sizing']},'market_overview':b['market_summary'],'records':records,'coverage':{'generated':len(records),'official_fundamentals':sum(disp[x['ticker']]['evidence_state']=='EVIDENCE_QUALIFIED' for x in records),'provider_descriptive':sum(disp[x['ticker']]['raw_observation_state']=='RAW_OBSERVED' for x in records),'technical_complete':len(records),'proxy_valuation':sum(r.get('mva_provider_proxy_valuation',{}).get('status')!='MISSING' for r in b['records'] if r.get('empirical_active_cohort_member'))},'safety_envelope':{'is_actionable_for_execution':False,'pit_backtest_eligible':False,'liquidity_sizing_authority':'BLOCKED','valuation_scope':'CURRENT_DESCRIPTIVE_ONLY'},'ticker_specific_branch_audit':{'status':'PASS','production_ticker_literals':[]},'gate':'MVA_RESEARCH_SYNTHESIS_READY','next_milestone':'P3-F19 EVIDENCE-AWARE MVA RESEARCH REVIEW WORKFLOW','verdict':'P3F18_MVA_RESEARCH_SYNTHESIS_COMPLETE'};a['artifact_sha256']=hashlib.sha256(json.dumps(a,sort_keys=True,separators=(',',':')).encode()).hexdigest();a['artifact_identity']='p3f18_mva_research_synthesis:'+a['artifact_sha256'];return a
