"""Close/high/low based current descriptive price-structure context; no PIT or signal authority."""
from __future__ import annotations
import hashlib,json
from collections import Counter
from typing import Any,Mapping
LOOKBACK=20;NEAR=.02
def _canon(x):return json.dumps(x,ensure_ascii=False,sort_keys=True,separators=(',',':'))
def _hash(x):return hashlib.sha256(_canon(x).encode()).hexdigest()
def build(snapshot:Mapping[str,Any],product:Mapping[str,Any],review:Mapping[str,Any])->dict[str,Any]:
    records=[];daily={x['ticker']:x for x in product['stock_research']}
    for ticker in sorted(daily):
        raw=snapshot['records'].get(ticker,{}); obs=raw.get('observations',[])
        if raw.get('status')!='OBSERVED' or len(obs)<LOOKBACK:
            records.append({'ticker':ticker,'research_session':product['daily_market_research']['session'],'structure_status':'INSUFFICIENT_HISTORY','reason':'COMPLETE_20_SESSION_HISTORY_REQUIRED'});continue
        prior=obs[:-1]; current=obs[-1]; close=float(current['close']); high=max(float(x['close']) for x in prior); low=min(float(x['close']) for x in prior); rng=high-low
        dist_high=(close/high)-1;dist_low=(close/low)-1;pos=(close-low)/rng if rng else None; state='IN_RANGE'
        if close>high: state='BREAKOUT_CONFIRMED_BY_RULE'
        elif close>=high*(1-NEAR):state='NEAR_RECENT_RESISTANCE'
        elif close<low:state='BREAKDOWN_CONFIRMED_BY_RULE'
        elif close<=low*(1+NEAR):state='NEAR_RECENT_SUPPORT'
        first=obs[:10];last=obs[10:]; old=max(float(x['close']) for x in first)-min(float(x['close']) for x in first);new=max(float(x['close']) for x in last)-min(float(x['close']) for x in last); range_state='RANGE_COMPRESSION' if new<=old*.7 else 'RANGE_EXPANSION' if new>=old*1.3 else 'RANGE_STABLE'
        rv=daily[ticker]['research_summary']['provider_relative_volume']; volume='ELEVATED_PROVIDER_RELATIVE_VOLUME_PROXY' if isinstance(rv,(int,float)) and rv>=1.5 else 'NO_ELEVATED_VOLUME_PROXY'
        records.append({'ticker':ticker,'research_session':current['session'],'structure_status':state,'range_state':range_state,'trend_structure_state':daily[ticker]['research_summary']['trend_state'],'levels':{'prior_19_session_close_resistance':{'value':high,'distance_from_close':dist_high,'source_series':'close','basis':current['price_basis'],'level_session_cutoff':prior[-1]['session'],'qualification':'DETERMINISTIC_CANDIDATE_NOT_PREDICTIVE'},'prior_19_session_close_support':{'value':low,'distance_from_close':dist_low,'source_series':'close','basis':current['price_basis'],'level_session_cutoff':prior[-1]['session'],'qualification':'DETERMINISTIC_CANDIDATE_NOT_PREDICTIVE'}},'range_position':pos,'volume_proxy_state':volume,'method':{'identity':'price_structure_breakout_context/v1','lookback_sessions':20,'prior_level_observations':19,'level_series':'close_only; retained high_low_scale_incompatible_and_not_used','current_bar_excluded_from_prior_levels':True,'near_threshold':NEAR,'price_basis':current['price_basis']},'authority_tier':'SHADOW_ONLY','warnings':['CURRENT_DESCRIPTIVE_ADJUSTED_RETROSPECTIVE_NOT_RAW_AS_TRADED','NOT_PIT_OR_BACKTEST_ELIGIBLE','RETAINED_HIGH_LOW_SCALE_INCOMPATIBLE_NOT_USED','PROVIDER_RELATIVE_VOLUME_PROXY_NOT_LIQUIDITY']})
    counts=Counter(x['structure_status'] for x in records);ranges=Counter(x.get('range_state','INSUFFICIENT_HISTORY') for x in records);pre={ 'NEAR_RECENT_RESISTANCE':counts['NEAR_RECENT_RESISTANCE'],'BREAKOUT_RESEARCH_CONTEXT':counts['BREAKOUT_CONFIRMED_BY_RULE'],'NEAR_RECENT_SUPPORT':counts['NEAR_RECENT_SUPPORT'],'BREAKDOWN_RESEARCH_CONTEXT':counts['BREAKDOWN_CONFIRMED_BY_RULE'],'RANGE_COMPRESSION_CONTEXT':ranges['RANGE_COMPRESSION']}
    out={'schema_version':'1.0.0','contract_version':'price_structure_breakout_context/v1','research_session':product['daily_market_research']['session'],'source_artifact_identities':{'exact_session_snapshot':snapshot['snapshot_identity'],'daily_product':product['artifact_identity']},'cohort':{'member_count':len(records),'authority':'EMPIRICAL_ACTIVE_SHADOW_ONLY'},'records':records,'coverage':{'usable_history_count':sum(x['structure_status']!='INSUFFICIENT_HISTORY' for x in records),'insufficient_history_count':counts['INSUFFICIENT_HISTORY'],'rolling_50_session_available_count':0,'rolling_50_session_unavailable_reason':'RETAINED_EXACT_SESSION_SERIES_CONTAINS_20_OBSERVATIONS_ONLY','structure_counts':dict(counts),'range_counts':dict(ranges),'elevated_volume_proxy_count':sum(x.get('volume_proxy_state')=='ELEVATED_PROVIDER_RELATIVE_VOLUME_PROXY' for x in records)},'screener_discovery_presets':pre,'authority_boundary':{'not_signal_recommendation_or_expected_return':True,'historical_pit_raw_as_traded_backtest':'NOT_PROMOTED','volume_proxy_not_liquidity':True},'verdict':'PRICE_STRUCTURE_BREAKOUT_RESEARCH_V1_READY'};out['artifact_identity']='price_structure_breakout_context:'+_hash(out);return out
def daily_overlay(context:Mapping[str,Any])->dict[str,Any]:
    out={'contract_version':'price_structure_daily_research_overlay/v1','price_structure_identity':context['artifact_identity'],'records':[{'ticker':x['ticker'],'research_session':x['research_session'],'price_structure_state':x['structure_status'],'range_state':x.get('range_state'),'trend_structure_state':x.get('trend_structure_state'),'authority_tier':x.get('authority_tier'),'warnings':x.get('warnings',[])} for x in context['records']]};out['artifact_identity']='price_structure_daily_research_overlay:'+_hash(out);return out
def scenario_overlay(context:Mapping[str,Any],scenarios:Mapping[str,Any])->dict[str,Any]:
    by={x['ticker']:x for x in context['records']}; eligible={x['ticker'] for x in scenarios['scenarios']}
    out={'contract_version':'price_structure_scenario_fact_overlay/v1','price_structure_identity':context['artifact_identity'],'entries':[{'ticker':t,'classification':'FACT','price_structure':{'state':by[t]['structure_status'],'range_state':by[t].get('range_state'),'trend_structure_state':by[t].get('trend_structure_state'),'source_identity':context['artifact_identity']},'warning':'DESCRIPTIVE_CURRENT_TECHNICAL_CONTEXT_NOT_A_FORECAST_OR_PROBABILITY'} for t in sorted(eligible)]};out['artifact_identity']='price_structure_scenario_fact_overlay:'+_hash(out);return out
def review_overlay(context:Mapping[str,Any],review:Mapping[str,Any])->dict[str,Any]:
    by={x['ticker']:x for x in context['records']};out={'contract_version':'price_structure_review_overlay/v1','price_structure_identity':context['artifact_identity'],'entries':[{'ticker':x['ticker'],'section':'PRICE_STRUCTURE','structure':by[x['ticker']]} for x in review['owner_review_queue']]};out['artifact_identity']='price_structure_review_overlay:'+_hash(out);return out
