"""Fail-closed market risk and liquidity metrics."""
from __future__ import annotations
import math
VERSION="1.0.0"
def out(n,state="unavailable",**k):
 x={"metric":n,"method_version":VERSION,"state":state,"applicability":"unknown","observation_window":None,"as_of_date":None,"source":None,"provenance":{},"required_inputs":[],"used_inputs":[],"missing_inputs":[],"calculation_assumptions":[],"value":None,"unit":None,"benchmark":None,"warnings":[],"interpretation_limits":[],"is_actionable":False};x.update(k);return x
def evaluate_market_risk(d,reference_at=None):
 d=d if isinstance(d,dict) else {}; rows=d.get("ohlcv") if isinstance(d.get("ohlcv"),list) else []; adjusted=d.get("price_adjustment")=="qualified";volume_units=d.get("volume_units")=="qualified"
 if not adjusted or len(rows)<3:return {"schema_version":VERSION,"reference_at":reference_at,"market_risk":{"realized_volatility":out("realized_volatility",missing_inputs=["qualified_adjusted_price_series"],warnings=["Do not mix adjusted and unadjusted returns."]),"downside_volatility":out("downside_volatility"),"maximum_drawdown":out("maximum_drawdown")},"liquidity_risk":{"average_volume":out("average_volume",missing_inputs=["qualified_volume_units"]),"days_to_liquidate":out("days_to_liquidate",missing_inputs=["user_order_size_and_participation_rate"])} ,"portfolio_risk":{"state":"unavailable","reason":"holdings_contract_absent"},"backtest_summary":{"state":"unavailable","reason":"point_in_time_signals_absent"}}
 closes=[float(x["close"]) for x in rows if x.get("close") not in (None,0)];rets=[closes[i]/closes[i-1]-1 for i in range(1,len(closes))];mean=sum(rets)/len(rets);vol=(sum((x-mean)**2 for x in rets)/len(rets))**.5;down=(sum(min(0,x)**2 for x in rets)/len(rets))**.5;peak=closes[0];mdd=0
 for c in closes:peak=max(peak,c);mdd=min(mdd,c/peak-1)
 liq=out("average_volume","available" if volume_units else "unavailable",value=sum(float(x.get("volume",0)) for x in rows)/len(rows) if volume_units else None,unit="provider_volume_units",warnings=[] if volume_units else ["volume_units_unqualified"])
 return {"schema_version":VERSION,"reference_at":reference_at,"market_risk":{"realized_volatility":out("realized_volatility","available",value=vol,unit="per_observation_return",is_actionable=bool(d.get("current_actionable"))),"downside_volatility":out("downside_volatility","available",value=down,unit="per_observation_return"),"maximum_drawdown":out("maximum_drawdown","available",value=mdd,unit="fraction")},"liquidity_risk":{"average_volume":liq,"days_to_liquidate":out("days_to_liquidate",missing_inputs=["user_order_size_and_participation_rate"])},"portfolio_risk":{"state":"unavailable","reason":"holdings_contract_absent"},"backtest_summary":{"state":"unavailable","reason":"point_in_time_signals_absent"}}
