"""Deterministic structured scenario evidence; never creates investment narratives."""
from __future__ import annotations
from typing import Any,Mapping
VERSION="1.0.0"
def rec(name,state="unknown",**kw):
 x={"scenario_name":name,"state":state,"thesis":None,"supporting_facts":[],"supporting_inferences":[],"contradicting_evidence":[],"required_conditions":[],"observable_confirmation_signals":[],"invalidation_conditions":[],"affected_domains":[],"source_provenance_references":[],"freshness_readiness_summary":{},"is_actionable":False};x.update(kw);return x
def evaluate_scenario_analysis(data:Mapping[str,Any]|None,reference_at:str|None=None):
 d=data if isinstance(data,Mapping) else {};fresh=d.get("freshness") if isinstance(d.get("freshness"),Mapping) else {};ready=d.get("readiness") if isinstance(d.get("readiness"),Mapping) else {};events=d.get("corporate_events") if isinstance(d.get("corporate_events"),Mapping) else {};ci=d.get("corporate_intelligence") if isinstance(d.get("corporate_intelligence"),Mapping) else {};technical=d.get("technical") if isinstance(d.get("technical"),Mapping) else {}
 market=fresh.get("daily_prices") if isinstance(fresh.get("daily_prices"),Mapping) else {}; tech=fresh.get("technical_signals") if isinstance(fresh.get("technical_signals"),Mapping) else {};current=market.get("is_actionable") is True and tech.get("is_actionable") is True and ready.get("market_technical",{}).get("state")=="ready"
 warnings=[];unknowns=[]
 if not current: warnings.append("market_technical_not_ready_or_current");unknowns.append("current_technical_confirmation")
 if events.get("coverage_status")=="partial_unqualified_50_row_cap":warnings.append("corporate_events_partial_unqualified_50_row_cap")
 if ci.get("status") not in {"available","partial"}:unknowns.append("corporate_intelligence")
 bull=rec("bull", "available" if current and technical.get("above_sma50") is True else "unknown", thesis="Technical confirmation is conditional, not a business-quality fact." if current and technical.get("above_sma50") is True else None, supporting_facts=[{"field":"above_sma50","value":True,"kind":"Fact"}] if current and technical.get("above_sma50") is True else [], supporting_inferences=["Trend continuation is an inference." ] if current and technical.get("above_sma50") is True else [], required_conditions=["current technical freshness", "above_sma50 remains true"], observable_confirmation_signals=["above_sma50"], invalidation_conditions=["above_sma50 becomes false"], affected_domains=["market_technical"], freshness_readiness_summary={"current":current}, is_actionable=current and technical.get("above_sma50") is True)
 bear=rec("bear", "available" if current and technical.get("above_sma50") is False else "unknown", thesis="Trend invalidation is conditional, not a target-price claim." if current and technical.get("above_sma50") is False else None, supporting_facts=[{"field":"above_sma50","value":False,"kind":"Fact"}] if current and technical.get("above_sma50") is False else [], supporting_inferences=["Trend weakness is an inference." ] if current and technical.get("above_sma50") is False else [], required_conditions=["current technical freshness"], observable_confirmation_signals=["above_sma50"], invalidation_conditions=["above_sma50 becomes true"], affected_domains=["market_technical"], freshness_readiness_summary={"current":current}, is_actionable=current and technical.get("above_sma50") is False)
 base=rec("base", "limited" if current else "unknown", thesis="No valuation, probability, or recommendation is implied.", required_conditions=["current technical freshness"], affected_domains=["market_technical","valuation"], freshness_readiness_summary={"current":current}, is_actionable=False)
 return {"schema_version":VERSION,"engine_version":VERSION,"reference_at":reference_at,"state":"available" if current else "unknown","is_actionable":any(x["is_actionable"] for x in (bull,bear,base)),"evidence_inventory":{"facts":bull["supporting_facts"]+bear["supporting_facts"],"data_warnings":warnings,"unknowns":unknowns,"inferences":bull["supporting_inferences"]+bear["supporting_inferences"],"hypotheses":[]},"data_warnings":warnings,"unknowns":unknowns,"scenarios":{"bear":bear,"base":base,"bull":bull},"catalysts":[],"downside_risks":["technical_trend_invalidation"] if bear["is_actionable"] else [],"invalidation_conditions":bear["invalidation_conditions"]+bull["invalidation_conditions"],"time_horizon":"current_market_observation_only","confidence_state":"limited" if current else "unknown","interpretation_limits":["No numerical probability, target price, recommendation, or inference from absent events."]}
