"""Deterministic structured scenario evidence; never creates investment narratives."""
from __future__ import annotations
from typing import Any, Mapping
VERSION="1.1.0"

def rec(name, state="unknown", **kw):
    x={"scenario_name":name,"state":state,"thesis":None,"supporting_facts":[],"supporting_inferences":[],"contradicting_evidence":[],"required_conditions":[],"observable_confirmation_signals":[],"catalysts":[],"downside":[],"invalidation_conditions":[],"time_horizon":"current_market_observation_only","affected_domains":[],"source_provenance_references":[],"freshness_readiness_summary":{},"is_actionable":False};x.update(kw);return x

def evaluate_scenario_analysis(data:Mapping[str,Any]|None,reference_at:str|None=None):
    d=data if isinstance(data,Mapping) else {};fresh=d.get("freshness") if isinstance(d.get("freshness"),Mapping) else {};ready=d.get("readiness") if isinstance(d.get("readiness"),Mapping) else {};events=d.get("corporate_events") if isinstance(d.get("corporate_events"),Mapping) else {};ci=d.get("corporate_intelligence") if isinstance(d.get("corporate_intelligence"),Mapping) else {};technical=d.get("technical") if isinstance(d.get("technical"),Mapping) else {};opportunity=d.get("opportunity") if isinstance(d.get("opportunity"),Mapping) else {};dimensions=opportunity.get("dimensions") if isinstance(opportunity.get("dimensions"),Mapping) else {}
    market=fresh.get("daily_prices") if isinstance(fresh.get("daily_prices"),Mapping) else {};tech=fresh.get("technical_signals") if isinstance(fresh.get("technical_signals"),Mapping) else {};current=market.get("is_actionable") is True and tech.get("is_actionable") is True and ready.get("market_technical",{}).get("state")=="ready"
    warnings=[]; unknowns=[]
    if not current: warnings.append("market_technical_not_ready_or_current");unknowns.append("current_technical_confirmation")
    if events.get("coverage_status")=="partial_unqualified_50_row_cap":warnings.append("corporate_events_partial_unqualified_50_row_cap")
    if ci.get("status") not in {"available","partial"}:unknowns.append("corporate_intelligence")
    for dimension in dimensions.values():
        if isinstance(dimension,Mapping): warnings.extend(str(x) for x in dimension.get("data_warnings",[]) if x not in warnings)
    catalyst=(dimensions.get("catalyst_evidence") or {}).get("facts",[]) if isinstance(dimensions.get("catalyst_evidence"),Mapping) else []
    downside=(dimensions.get("downside_invalidation") or {}).get("facts",[]) if isinstance(dimensions.get("downside_invalidation"),Mapping) else []
    financial=(dimensions.get("financial_quality") or {}).get("facts",[]) if isinstance(dimensions.get("financial_quality"),Mapping) else []
    valuation=(dimensions.get("valuation") or {}).get("facts",[]) if isinstance(dimensions.get("valuation"),Mapping) else []
    facts=financial+valuation+([{"field":"above_sma50","value":technical.get("above_sma50"),"kind":"Fact"}] if current and isinstance(technical.get("above_sma50"),bool) else [])
    bull=rec("bull", "available" if current and technical.get("above_sma50") is True else "unknown", thesis="Technical confirmation is conditional, not a business-quality fact." if current and technical.get("above_sma50") is True else None, supporting_facts=facts if current and technical.get("above_sma50") is True else [], supporting_inferences=["Trend continuation is an inference."] if current and technical.get("above_sma50") is True else [], required_conditions=["current technical freshness", "above_sma50 remains true"], observable_confirmation_signals=["above_sma50"], catalysts=catalyst, downside=downside, invalidation_conditions=["above_sma50 becomes false"], affected_domains=["market_technical","financial_quality","valuation"], freshness_readiness_summary={"current":current}, is_actionable=current and technical.get("above_sma50") is True)
    bear=rec("bear", "available" if current and technical.get("above_sma50") is False else "unknown", thesis="Trend invalidation is conditional, not a target-price claim." if current and technical.get("above_sma50") is False else None, supporting_facts=facts if current and technical.get("above_sma50") is False else [], supporting_inferences=["Trend weakness is an inference."] if current and technical.get("above_sma50") is False else [], required_conditions=["current technical freshness"], observable_confirmation_signals=["above_sma50"], catalysts=[], downside=downside, invalidation_conditions=["above_sma50 becomes true"], affected_domains=["market_technical","financial_quality","valuation"], freshness_readiness_summary={"current":current}, is_actionable=current and technical.get("above_sma50") is False)
    base_state="limited" if any((dimensions.get(name) or {}).get("state")=="available" for name in ("financial_quality","valuation","technical_current_market_readiness")) else "unknown"
    base=rec("base", base_state, thesis="No valuation, probability, or recommendation is implied.", supporting_facts=financial+valuation, required_conditions=["qualified facts remain internally consistent"], catalysts=catalyst, downside=downside, invalidation_conditions=["qualified fact becomes stale, conflicting, or unavailable"], affected_domains=["financial_quality","valuation","market_technical"], freshness_readiness_summary={"current":current}, is_actionable=False)
    return {"schema_version":VERSION,"engine_version":VERSION,"reference_at":reference_at,"state":"available" if current else "partial" if base_state=="limited" else "unknown","is_actionable":any(x["is_actionable"] for x in (bull,bear,base)),"evidence_inventory":{"facts":facts,"data_warnings":warnings,"unknowns":unknowns,"inferences":bull["supporting_inferences"]+bear["supporting_inferences"],"hypotheses":[]},"data_warnings":warnings,"unknowns":unknowns,"scenarios":{"bear":bear,"base":base,"bull":bull},"catalysts":catalyst,"downside_risks":downside,"invalidation_conditions":bear["invalidation_conditions"]+bull["invalidation_conditions"],"time_horizon":"current_market_observation_only","confidence_state":(dimensions.get("data_confidence") or {}).get("state","unknown"),"interpretation_limits":["No numerical probability, target price, recommendation, or inference from absent events."]}
