"""Promote the fixed HPG/PVD FY2022-FY2023 official-financial evidence pilot.

The module does not acquire data, read a provider, or write the database.  It turns the
four already retained, hash-addressed issuer filings and their page materializations into
the existing append-only evidence-promotion request.  It is deliberately explicit so the
pilot cohort, periods, values, and page citations are reviewable as one bounded contract.
"""
from __future__ import annotations

import argparse
import json
import os
from pathlib import Path
from typing import Any

import evidence_promotion as promotion
from annual_financial_ocr_materialization import verified_debt_extraction, verified_extraction


VERSION = "1.0.0"
DEFAULT_EVIDENCE_ROOT = Path("operations-review") / "governed-official-evidence-v1"
MATERIALIZATION_ROOT = Path("derived") / "annual_financial_ocr_materialization_v1"
VERIFIED_AT = "2026-08-09T00:00:00Z"

# The cohort is fixed after selection: HPG is the retained-control issuer and PVD is the
# newer audited-statement/OCR path.  No fallback ticker is encoded here.
PILOT: dict[str, dict[str, Any]] = {
    "657f9069c41deb37b3611fe366ef49da507d6ac2651db0df332f09340ad9449d": {
        "sidecar": "hpg-fy2023.json", "issuer": "Hoa Phat Group Joint Stock Company",
        "authority_domain": "hoaphat.com.vn",
        "title": "Hoa Phat Group Annual Report 2023 — audited consolidated financial statements",
        "currency": "VND",
        "facts": {
            "cash_and_equivalents": (12_252_001_160_884, 83, "Cash and cash equivalents", "12,252,001,160,884", "balance_sheet"),
            "shareholders_equity": (102_836_419_239_379, 87, "EQUITY", "102,836,419,239,379", "balance_sheet"),
            "net_income": (6_800_388_315_081, 88, "Net profit after tax", "6,800,388,315,081", "income_statement"),
            "operating_cash_flow": (8_643_030_777_026, 90, "Net cash flows from operating activities", "8,643,030,777,026", "cash_flow"),
        },
        "debt": [(86, "Short-term borrowings", "54,981,883,180,636", "short_term_borrowings"),
                 (86, "Long-term borrowings", "10,399,119,292,481", "long_term_borrowings_or_finance_leases")],
    },
    "5c29d7868c552bb25760d684d11b44db9ad74d0348407a5949e903815b860114": {
        "sidecar": "hpg-fy2022.json", "issuer": "Hoa Phat Group Joint Stock Company",
        "authority_domain": "hoaphat.com.vn",
        "title": "Hoa Phat Group Annual Report 2022 — audited consolidated financial statements",
        "currency": "VND",
        "facts": {
            "cash_and_equivalents": (8_324_588_920_227, 102, "Cash and cash equivalents", "8,324,588,920,227", "balance_sheet"),
            "shareholders_equity": (96_112_939_615_783, 105, "EQUITY", "96,112,939,615,783", "balance_sheet"),
            "net_income": (8_444_429_054_516, 106, "Net profit after tax", "8,444,429,054,516", "income_statement"),
            "operating_cash_flow": (12_277_636_676_507, 108, "Net cash flows from operating activities", "12,277,636,676,507", "cash_flow"),
        },
        "debt": [(104, "Short-term borrowings", "46,748,670,400,471", "short_term_borrowings"),
                 (104, "Long-term borrowings", "11,151,651,204,402", "long_term_borrowings_or_finance_leases")],
    },
    "0a3a11d700b0936621fb1ebd768a38a7d0b528bd82cab5ed34cd29b1036bde96": {
        "sidecar": "pvd-fy2023.json", "issuer": "Petrovietnam Drilling and Well Services Corporation",
        "authority_domain": "pvdrilling.com.vn", "title": "PV Drilling Audited Consolidated Financial Statements 2023",
        "currency": "USD",
        "facts": {
            "cash_and_equivalents": (93_689_666, 6, "Cash and cash equivalents", "93,689,666", "balance_sheet"),
            "shareholders_equity": (618_694_250, 7, "D. EQUITY", "618,694,250", "balance_sheet"),
            "net_income": (23_061_808, 8, "Net profit/(loss) after corporate income tax", "23,061,808", "income_statement"),
            "operating_cash_flow": (66_483_986, 9, "Net cash generated by", "66,483,986", "cash_flow"),
        },
        "debt": [(7, "Short-term loans", "22,979,768", "short_term_borrowings"),
                 (7, "Long-term loans", "115,767,517", "long_term_borrowings_or_finance_leases")],
    },
    "f125cc40f2db2a3ccb0abea24f42e4939f7d0b4e7559d1270de51026df16aecf": {
        "sidecar": "pvd-fy2022.json", "issuer": "Petrovietnam Drilling and Well Services Corporation",
        "authority_domain": "pvdrilling.com.vn", "title": "PV Drilling Audited Consolidated Financial Statements 2022",
        "currency": "USD",
        "facts": {
            "cash_and_equivalents": (88_790_540, 6, "Cash and cash equivalents", "88,790,540", "balance_sheet"),
            "shareholders_equity": (601_388_693, 7, "D. EQUITY", "601,388,693", "balance_sheet"),
            "net_income": (-6_653_052, 8, "Net (loss)/profit after corporate income tax", "(6,653,052)", "income_statement"),
            "operating_cash_flow": (-3_587_361, 9, "Net cash used in operating activities", "(3,587,361)", "cash_flow"),
        },
        "debt": [(7, "Short-term loans", "35,682,060", "short_term_borrowings"),
                 (7, "Long-term loans", "128,139,772", "long_term_borrowings_or_finance_leases")],
    },
}


def _records(evidence_root: Path) -> dict[str, dict[str, Any]]:
    manifest = json.loads((evidence_root / "official_document_acquisition_manifest.json").read_text(encoding="utf-8"))
    return {str(row["document_id"]): row for row in manifest.get("records") or []}


def build_promotion(evidence_root: Path = DEFAULT_EVIDENCE_ROOT) -> tuple[list[dict[str, Any]], list[dict[str, Any]]]:
    """Build, but do not write, the exact four evidence records and twenty identity citations."""
    evidence_root = Path(evidence_root)
    records = _records(evidence_root)
    manifest_records, citations = [], []
    for document_id, spec in PILOT.items():
        record = records.get(document_id)
        if record is None or record.get("acquisition_status") != "retained":
            raise ValueError(f"PILOT_DOCUMENT_NOT_RETAINED:{document_id}")
        evidence_id = promotion._hash({"ticker": record["ticker"], "document_sha256": record["sha256"], "document_id": document_id})
        manifest_records.append(promotion.build_manifest_record(
            evidence_id=evidence_id, archive_document_path=evidence_root / record["relative_path"], sha256=record["sha256"],
            filename=Path(record["relative_path"]).name, ticker=record["ticker"], issuer=spec["issuer"],
            authority=record["source_authority"], authority_domain=spec["authority_domain"],
            evidence_type="audited_consolidated_financial_statements", source_url=record["canonical_url"],
            document_title=spec["title"], document_id=document_id, document_class=record["document_class"],
            reporting_period=record["reporting_period"], published_at=record["published_at"], observed_at=record["observed_at"],
            statement_scope="consolidated", audit_status="audited", source_id=record["source_id"],
        ))
        materialization = json.loads((evidence_root / MATERIALIZATION_ROOT / spec["sidecar"]).read_text(encoding="utf-8"))
        for metric, (value, page, label, raw_value, statement) in spec["facts"].items():
            extraction = verified_extraction(materialization, page=page, raw_label=label, raw_value=raw_value,
                                             unit=spec["currency"], statement=statement, visual_source_page_verified=True)
            citations.append(promotion.build_financial_identity_citation(
                ticker=record["ticker"], metric=metric, reporting_period=record["reporting_period"], value=value,
                evidence_id=evidence_id, currency=spec["currency"],
                citation=f"Issuer PDF page {page}; audited consolidated FY{record['reporting_period']}.",
                verified_at=VERIFIED_AT, extraction=extraction,
            ))
        components = [{"page": page, "label": label, "raw_value": raw_value, "component_type": component_type,
                       "reporting_period": record["reporting_period"], "visual_source_page_verified": True}
                      for page, label, raw_value, component_type in spec["debt"]]
        debt = verified_debt_extraction(materialization, components=components, unit=spec["currency"],
                                        statement="balance_sheet", reporting_period=record["reporting_period"])
        citations.append(promotion.build_financial_identity_citation(
            ticker=record["ticker"], metric="total_interest_bearing_debt", reporting_period=record["reporting_period"],
            value=debt["normalized_value"], evidence_id=evidence_id, currency=spec["currency"],
            citation=f"Issuer PDF page {debt['source_pages'][0]}; audited consolidated FY{record['reporting_period']}; short- and long-term borrowing components.",
            verified_at=VERIFIED_AT, extraction=debt,
        ))
    return manifest_records, citations


def promote_pilot(runtime_root: Path, *, evidence_root: Path = DEFAULT_EVIDENCE_ROOT, dry_run: bool = True) -> dict[str, Any]:
    manifest_records, citations = build_promotion(evidence_root)
    return promotion.promote(Path(runtime_root), manifest_records=manifest_records,
                             citation_relative=promotion.FINANCIAL_IDENTITY_RELATIVE,
                             citation_records=citations, dry_run=dry_run)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--runtime-root", type=Path, default=os.environ.get("STOCK_LOOKUP_RUNTIME_ROOT"))
    parser.add_argument("--evidence-root", type=Path, default=DEFAULT_EVIDENCE_ROOT)
    parser.add_argument("--promote", action="store_true", help="append through evidence_promotion; default is dry run")
    args = parser.parse_args(argv)
    if args.runtime_root is None:
        parser.error("--runtime-root or STOCK_LOOKUP_RUNTIME_ROOT is required")
    print(json.dumps(promote_pilot(args.runtime_root, evidence_root=args.evidence_root, dry_run=not args.promote), sort_keys=True))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
