"""Build the current lane-preserving opportunity priority artifact from retained inputs."""
from __future__ import annotations
import json,sys
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1];sys.path.insert(0,str(ROOT));OPS=ROOT/'operations-review';OUT=OPS/'current-opportunity-prioritization-v1-20260824'
from current_opportunity_prioritization import build,replay
from current_evidence_bound_scenario import build as scenario_build
from market_wide_current_corporate_intelligence import build as ci_build
from polymorphic_current_strategy_classification import build as strategy_build
P={"official_universe":"current-official-market-universe-integration-v1-20260824/current_official_market_universe_artifact.json","event_context":"current-official-event-context-integration-v1-20260824/current_official_event_context_artifact.json","descriptive":"market-wide-current-technical-coverage-scaleout-v1-20260823/market_wide_current_descriptive_research_artifact.json","screening":"current-market-screening-opportunity-comparison-foundation-v1-20260823/current_market_screening_opportunity_comparison_foundation_artifact.json","tactical":"watchlist-tactical-entry-decision-v1-20260823/watchlist_tactical_entry_classifier_artifact.json","peer":"sector-aware-relative-research-v1-20260824/sector_aware_relative_research_artifact.json","fundamental":"market-wide-current-fundamental-research-v1-20260823/market_wide_current_fundamental_research_artifact.json","valuation":"market-wide-current-valuation-v1-20260824/market_wide_current_valuation_artifact.json","triage":"full-universe-entry-candidate-triage-20260824/full_universe_entry_candidate_triage_20260824.json","catalyst":"catalyst-event-research-context-v1-20260820/catalyst_event_research_context_artifact.json","strategy_old":"polymorphic-current-strategy-classification-v1-20260824/polymorphic_current_strategy_classification_artifact.json","daily":"current-daily-decision-research-product-v2-20260824/current_daily_decision_research_product_artifact.json"}
def main():
 d={k:json.loads((OPS/v).read_text(encoding='utf8')) for k,v in P.items()};s=d['descriptive']['session'];ci=ci_build(descriptive=d['descriptive'],fundamental=d['fundamental'],session=s,root=ROOT,official_event_context=d['event_context']);sc=scenario_build(descriptive=d['descriptive'],tactical=d['tactical'],peer_relative=d['peer'],fundamental=d['fundamental'],valuation=d['valuation'],triage=d['triage'],catalyst=d['catalyst'],screening=d['screening'],corporate_intelligence=ci);st=strategy_build(descriptive=d['descriptive'],tactical=d['tactical'],peer_relative=d['peer'],fundamental=d['fundamental'],valuation=d['valuation'],scenario=sc,corporate_intelligence=ci);a=build(official_universe=d['official_universe'],screening=d['screening'],tactical=d['tactical'],strategy=st,scenario=sc,fundamental=d['fundamental'],peer=d['peer'],event_context=d['event_context'],descriptive=d['descriptive']);replay(a)
 old={t for t,r in d['strategy_old']['records'].items() if 'EVENT_DRIVEN' in r.get('eligible_strategy_ids',[])};new={t for t,r in st['records'].items() if 'EVENT_DRIVEN' in r.get('eligible_strategy_ids',[])};high=set(d['daily']['high_priority_full_universe_review_set']['tickers']);now={t for t,r in a['records'].items() if r['priority_tier']=='PRIORITY_NOW'};a['daily_product_comparison']={"existing_high_priority":len(high),"agreement":len(high&now),"newly_surfaced":sorted(now-high),"downgraded":sorted(high-now),"compatibility":"READ_ONLY_TICKER_COMPARISON_NO_FROZEN_DAILY_OUTPUT_MUTATION"};a['event_driven_semantic_review']={"old_gate_count":len(old),"final_count":len(new),"past_event_satisfies_gate":False,"date_incomplete_satisfies_gate":False,"agm_only_satisfies_gate":False,"contract_result":"CURRENT_OFFICIAL_EVENT_REQUIRES_CURRENT_PRICE_SHARE_AFFECTING_EVENT; legacy current qualified CORPORATE_ACTION remains supported"};from current_opportunity_prioritization import content_identity;a.update(content_identity(a));replay(a);OUT.mkdir(parents=True,exist_ok=True);(OUT/'current_opportunity_prioritization_artifact.json').write_text(json.dumps(a,ensure_ascii=False,indent=2,sort_keys=True)+'\n',encoding='utf8');print(a['artifact_identity']);print(a['coverage']);print(a['event_driven_semantic_review'])
if __name__=='__main__':main()
