"""Materialize retained official event context and prove bounded current consumers."""
from __future__ import annotations
import hashlib
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]; sys.path.insert(0, str(ROOT))
from current_official_event_context import build_artifact, replay
from current_daily_decision_research_product import build as build_product
from current_evidence_bound_scenario import build as build_scenario
from market_wide_current_corporate_intelligence import build as build_ci, content_identity as ci_identity
from polymorphic_current_strategy_classification import build as build_strategy

OPS = ROOT / "operations-review"; OUT = OPS / "current-official-event-context-integration-v1-20260824"
PATHS = {"official_universe": OPS / "current-official-market-universe-integration-v1-20260824/current_official_market_universe_artifact.json", "hnx": OPS / "hnx-enumerable-universe-kllh-event-and-disclosure-scaleout-v1-20260824/hnx_enumerable_universe_artifact.json", "hose": OPS / "hose-public-xhr-and-periodic-series-recon-v1-20260824-reconciled/hose_public_xhr_artifact.json", "descriptive": OPS / "market-wide-current-technical-coverage-scaleout-v1-20260823/market_wide_current_descriptive_research_artifact.json", "screening": OPS / "current-market-screening-opportunity-comparison-foundation-v1-20260823/current_market_screening_opportunity_comparison_foundation_artifact.json", "tactical": OPS / "watchlist-tactical-entry-decision-v1-20260823/watchlist_tactical_entry_classifier_artifact.json", "peer_relative": OPS / "sector-aware-relative-research-v1-20260824/sector_aware_relative_research_artifact.json", "fundamental": OPS / "market-wide-current-fundamental-research-v1-20260823/market_wide_current_fundamental_research_artifact.json", "valuation": OPS / "market-wide-current-valuation-v1-20260824/market_wide_current_valuation_artifact.json", "triage": OPS / "full-universe-entry-candidate-triage-20260824/full_universe_entry_candidate_triage_20260824.json", "catalyst": OPS / "catalyst-event-research-context-v1-20260820/catalyst_event_research_context_artifact.json", "ci_before": OPS / "market-wide-current-corporate-intelligence-v1-20260824/market_wide_current_corporate_intelligence_artifact.json", "scenario_before": OPS / "current-evidence-bound-scenario-v1-20260824/current_evidence_bound_scenario_artifact.json", "strategy_before": OPS / "polymorphic-current-strategy-classification-v1-20260824/polymorphic_current_strategy_classification_artifact.json"}

def load(): return {name: json.loads(path.read_text(encoding="utf-8")) for name, path in PATHS.items()}
def identity(value): return hashlib.sha256(json.dumps(value, ensure_ascii=False, sort_keys=True, separators=(",", ":")).encode()).hexdigest()
def main():
    data = load(); session = data["descriptive"]["session"]
    context = build_artifact(official_universe=data["official_universe"], hnx=data["hnx"], hose=data["hose"], research_session=session); replay(context)
    ci = build_ci(descriptive=data["descriptive"], fundamental=data["fundamental"], session=session, root=ROOT, official_event_context=context)
    if ci_identity(ci)["artifact_sha256"] != ci["artifact_sha256"]: raise ValueError("CI_SELF_VERIFICATION_FAILED")
    scenario = build_scenario(descriptive=data["descriptive"], tactical=data["tactical"], peer_relative=data["peer_relative"], fundamental=data["fundamental"], valuation=data["valuation"], triage=data["triage"], catalyst=data["catalyst"], screening=data["screening"], corporate_intelligence=ci)
    strategy = build_strategy(descriptive=data["descriptive"], tactical=data["tactical"], peer_relative=data["peer_relative"], fundamental=data["fundamental"], valuation=data["valuation"], scenario=scenario, corporate_intelligence=ci)
    product = build_product(descriptive=data["descriptive"], tactical=data["tactical"], peer_relative=data["peer_relative"], fundamental=data["fundamental"], valuation=data["valuation"], scenario=scenario, triage=data["triage"], corporate_intelligence=ci, strategy_classification=strategy)
    events = set(context["records"]); ci_current = {event["ticker"] for event in context["corporate_intelligence_adapter"]["events"]}; screening_ready = {ticker for ticker,row in data["screening"]["records"].items() if row.get("market_relative_comparison", {}).get("status") == "AVAILABLE"}; tactical_classified = {ticker for ticker,row in data["tactical"]["records"].items() if row.get("entry_state") is not None}; entry_relevant = {ticker for ticker,row in data["tactical"]["records"].items() if row.get("entry_action") in {"EARLY_ENTRY", "BUY_ON_CONFIRMATION", "ACCUMULATE_IN_BASE"}}; strategy_eligible = {ticker for ticker,row in strategy["records"].items() if row.get("eligible_strategy_ids")}; scenario_ready = {ticker for ticker,row in scenario["records"].items() if row.get("scenario_disposition") in {"SCENARIO_READY", "SCENARIO_PARTIAL"}}
    before_event = sum("EVENT_DRIVEN" in row.get("eligible_strategy_ids", []) for row in data["strategy_before"]["records"].values()); after_event = sum("EVENT_DRIVEN" in row.get("eligible_strategy_ids", []) for row in strategy["records"].values())
    delta = [{"ticker": ticker, "market": data["official_universe"]["records"][ticker]["exchange_or_market"], "official_source": data["official_universe"]["records"][ticker]["official_source"], "known_exclusion_reason": data["official_universe"]["records"][ticker]["qualification"], "candidate_action": "REVIEW_FOR_FUTURE_ADDITION"} for ticker in data["official_universe"]["reconciliation"]["official_only_tickers"]]
    report = {"schema_version":"1.0.0", "contract_version":"current_official_event_context_integration/v1", "event_context_artifact_identity":context["artifact_identity"], "corporate_intelligence_artifact_identity":ci["artifact_identity"], "scenario_artifact_identity":scenario["artifact_identity"], "strategy_artifact_identity":strategy["artifact_identity"], "daily_product_artifact_identity":product["artifact_identity"], "coverage":context["coverage"], "ci_adapter":{"ready_before":data["ci_before"]["coverage"]["any_intelligence_coverage"], "ready_after":ci["coverage"]["any_intelligence_coverage"], "event_context_tickers":len(ci_current), "event_records_consumed":len(context["corporate_intelligence_adapter"]["events"])}, "overlap":{"screening_ready":len(events & screening_ready), "tactical_classified":len(events & tactical_classified), "entry_relevant":len(events & entry_relevant), "strategy_eligible":len(events & strategy_eligible), "scenario_ready_or_partial":len(events & scenario_ready)}, "event_driven":{"eligible_before":before_event, "eligible_after":after_event, "event_data_ready_but_other_gates_blocked":0, "rule":"Existing EVENT_DRIVEN rule has only CURRENT_OFFICIAL_EVENT as its required feature."}, "research_packet_result":"NOT_INTEGRATED_FROZEN_PACKET_SESSION_2026_08_20_MISMATCH; no compatible current-session packet adapter exists without changing its governed cohort.", "daily_research_compatibility":"COMPATIBLE_CURRENT_PRODUCT_EXTENSION; CI context passes through existing corporate_intelligence_context without changing product rules.", "scenario_event_mapping_result":"WIRED_THROUGH_EXISTING_CORPORATE_INTELLIGENCE_CATALYST_CONTEXT", "official_only_delta_review":delta, "authority_boundary":"FACTUAL_CURRENT_EVENT_CONTEXT_ONLY; publication timing unknown; no event scoring, impact, price adjustment, RAW_AS_TRADED, PIT, or backtest authority"}
    report["artifact_sha256"] = identity(report); report["artifact_identity"] = "current_official_event_context_integration:" + report["artifact_sha256"]
    candidate = dict(report); candidate.pop("artifact_sha256"); candidate.pop("artifact_identity")
    if identity(candidate) != report["artifact_sha256"]: raise ValueError("INTEGRATION_ARTIFACT_SELF_VERIFICATION_FAILED")
    OUT.mkdir(parents=True, exist_ok=True); (OUT / "current_official_event_context_artifact.json").write_text(json.dumps(context,ensure_ascii=False,indent=2,sort_keys=True)+"\n",encoding="utf-8"); (OUT / "current_official_event_context_integration_artifact.json").write_text(json.dumps(report,ensure_ascii=False,indent=2,sort_keys=True)+"\n",encoding="utf-8")
    print(context["artifact_identity"]); print(report["artifact_identity"]); print(report["ci_adapter"])
if __name__ == "__main__": main()
